"""Create letter table

Revision ID: c3a37985e3d2
Revises: 
Create Date: 2026-09-14 06:17:35.170749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a37985e3d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(length=100), nullable=False),
    sa.Column('recipient_email', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('letter')
    # ### end Alembic commands ###
